version: '3.8'

services:
  db:
    image: mysql:latest
    networks:
      - db-network
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  db-network:
    driver: bridge

volumes:
  mysql_data: